### PR TITLE
Small typo: encoded -> encoder

### PR DESCRIPTION
**Pull request by lindsaydbrin**
Resolve # (NA)

## Description:

Fixed small typo!

## Checklist:

You should check all boxes before the PR is ready. If a box does not apply, check it to acknowledge it.

* [x] **ISSUE NUMBER.** You linked the issue number (Ex: Resolve #XXX).
* [x] **PRE-COMMIT.** You ran pre-commit on all commits, or else, you
  ran `pre-commit run --all-files` at the end.
* [x] **FRONTEND TYPES.** Regenerate the front-ent types if you played with types and routes.
  Run `cd webapp && yarn types` while the back-end is running.
* [x] **USER CHANGES.** The changes are added to CHANGELOG.md and the documentation, if they impact
  our users.
* [x] **DEV CHANGES.**
    * Update the documentation if this PR changes how to develop/launch on the app.
    * Update the `README` files and our wiki for any big design decisions, if relevant.
    * Add unit tests, docstrings, typing and comments for complex sections.

### CODE REVIEW

**Review by gabegma — APPROVED** [review]
Don't hesitate to merge directly on main, if you have the option :)

**Comment by lindsaydbrin** [comment]
@gabegma What do you mean? Like, not wait for requirements to be met / tests to be conducted?

**Comment by lindsaydbrin** [comment]
Or, like, I don't need approval to fix a typo? :)

**Comment by gabegma** [comment]
> Or, like, I don't need approval to fix a typo? :)

exactly!

**Pull request merged**
