### PR TITLE
Update README.md to add more badges

### PR DESCRIPTION
**Pull request by Dref360**
## Checklist:

You should check all boxes before the PR is ready. If a box does not apply, check it to acknowledge
it.

* [x] **PRE-COMMIT.** You ran pre-commit on all commits, or else, you
  ran `pre-commit run --all-files` at the end.
* [x] **FRONTEND TYPES.** Regenerate the front-ent types if you played with types and routes.
  Run `cd webapp && yarn types` while the back-end is running.
* [x] **USER CHANGES.** The changes are added to CHANGELOG.md and the documentation, if they impact
  our users.
* [x] **DEV CHANGES.**
    * Update the documentation if this PR changes how to develop/launch on the app.
    * Update the `README` files and our wiki for any big design decisions, if relevant.
    * Add unit tests, docstrings, typing and comments for complex sections.

### CODE REVIEW

**Comment by gabegma** [comment]
What does it mean that the CI is currently failing?
Screen Shot 2022-04-20 at 4 29 28 PM

**Comment by Dref360** [comment]
because the test on main were failing :P hence my PR to add a timeout for faster failing

**Comment by gabegma** [comment]
> because the test on main were failing :P hence my PR to add a timeout for faster failing

So it wasn't failing because of a particular test, but because it was hanging somewhere?

**Review by gabegma — APPROVED** [review]

**Comment by Dref360** [comment]
No, I cancelled it manually after it was stuck for 4 hours.

**Pull request merged**
